In [5]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import scipy.integrate as inta

In [7]:
inta.quad(lambda x: x**2,0,1)

(0.33333333333333337, 3.700743415417189e-15)

## * Finding $R_{max}$

In [17]:
Nq = 200 #gain is 200 MeV
R = 2.5e+6 # Surface resistivity (ohm/square)
d = 100e-6 # Anode-readout plane separation (m)
eps_0 = 8.854e-12 # Permittivity of a vacuum (F/m)
k_1 = 3.3 # Relative permittivity of dielectric material (glue)
k_2 = 3.1 # Relative permittivity of dielectric material (mylar)
C = ((2*eps_0)/d)*((k_1*k_2)/(k_1+k_2)) # Capacitance per unit area with two dielectrics
h = 1/(R*C)
q = np.array([])
r = np.array([])
r = np.append(r,0)
i = 0 #to keep track of index
found = False 
while found == False:
    r = np.append(r,r[i]+1e-5)
    i += 1
    print(r,i)
    if i == 5:
        
        found = True

[0.e+00 1.e-05] 1
[0.e+00 1.e-05 2.e-05] 2
[0.e+00 1.e-05 2.e-05 3.e-05] 3
[0.e+00 1.e-05 2.e-05 3.e-05 4.e-05] 4
[0.e+00 1.e-05 2.e-05 3.e-05 4.e-05 5.e-05] 5
